# Generated by Django 2.2.24 on 2021-10-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0015_auto_20200916_1441"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(null=True)),
                ("api_key", models.CharField(max_length=100)),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_config",
                        to="environments.Environment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
